-- GENERATED by scripts/generate-doe-seed.py. Do not edit by hand.
--
-- Supabase loads this after every `db reset`, which is what stops a reset
-- destroying DOE data that was loaded by hand and saved nowhere else.
-- Regenerate after each load; see docs/doe-manual-load-procedure.md.
--
-- ON CONFLICT DO NOTHING so this is safe to apply to a database that
-- already holds these runs, rather than only to an empty one.

insert into public.doe_load_runs (id, doe_region_code, status, source_url, period_start, period_end, period_label, failure_reason, started_at, recorded_at) values
  ('460af9b5-0bab-49fa-b427-41662d170a0b', 'NCR', 'succeeded', 'https://prod-cms.doe.gov.ph/documents/d/guest/ncr-price-monitoring-08182026-pdf', '2026-08-18', '2026-08-24', '(For the week of August 18-24, 2026)', null, '2026-08-27 19:44:42.849411+00', '2026-08-27 19:44:42.849411+00'),
  ('7fe92b7c-5731-41d4-b4d4-2d32c1914d32', 'IV-A', 'succeeded', 'https://prod-cms.doe.gov.ph/documents/d/guest/region-iv-a-calabarzon-22-pdf', '2026-08-18', '2026-08-20', 'DATE MONITORING: August 18 - 20, 2026', null, '2026-08-27 19:44:42.600098+00', '2026-08-27 19:44:42.600098+00')
on conflict (id) do nothing;

insert into public.doe_locality_reports (id, run_id, doe_source_label, status) values
  ('152fee31-2882-4273-9221-7677c16cecef', '460af9b5-0bab-49fa-b427-41662d170a0b', 'Taguig Cty', 'data'),
  ('1cae152d-3be2-4e5b-a2d0-6ff261db6e20', '7fe92b7c-5731-41d4-b4d4-2d32c1914d32', 'Tanauan City', 'data'),
  ('1db4990c-094e-4fe9-ba3e-9c675b149ef1', '7fe92b7c-5731-41d4-b4d4-2d32c1914d32', 'Lipa City', 'data')
on conflict (id) do nothing;

insert into public.doe_reference_prices (id, locality_report_id, fuel_type_code, brand_code, min_price, max_price, common_price, brand_presence) values
  ('0b9beba1-791a-4385-a433-4861894f5d11', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'DIESEL', 'OVERALL', '85.50', '93.70', null, 'reported'),
  ('0de73529-e98b-41f0-9340-e495f29f5d2c', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_91', 'PTT', null, null, null, 'no_outlet'),
  ('25e1b64a-c447-43e7-93b9-da6a7baf7429', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_95', 'INDEPENDENT', '71.99', '71.99', null, 'reported'),
  ('33d475da-446c-400a-a43b-649494540f54', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_91', 'OVERALL', '71.49', '79.90', '74.40', 'reported'),
  ('3ac4cd0a-f4ca-46b3-a15b-97d1d5b4d663', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'DIESEL', 'PETRON', '88.10', '88.10', null, 'reported'),
  ('417df7a7-c30e-459f-893f-7861f71a0bac', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'RON_95', 'PETRON', '78.80', '78.80', null, 'reported'),
  ('528a1d9b-b43c-4c81-a84e-230f6cfc7a7a', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_95', 'FLYING_V', '72.00', '72.00', null, 'reported'),
  ('57bce40d-9035-47de-89ff-6e950b28c106', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'DIESEL', 'PETRON', '89.20', '89.20', null, 'reported'),
  ('5a169119-ec5e-44f6-bfe4-8456659f7de4', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'KEROSENE', 'CALTEX', '134.67', '134.67', null, 'reported'),
  ('5f4d5b07-cf0a-4aa3-a5d6-0d55155dd4dd', '152fee31-2882-4273-9221-7677c16cecef', 'RON_95', 'OVERALL', '72.40', '93.70', null, 'reported'),
  ('62aef72f-0e65-45b0-bc7a-ce57b8142e1a', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'RON_95', 'OVERALL', '71.50', '83.60', null, 'reported'),
  ('6540bb6b-e354-4b0d-a3a7-abeaf1ca3df6', '152fee31-2882-4273-9221-7677c16cecef', 'DIESEL', 'SHELL', '88.50', '93.70', '89.10', 'reported'),
  ('65addca7-0aff-407a-94c1-7f221ce5243c', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'RON_95', 'CALTEX', '83.60', '83.60', null, 'reported'),
  ('67e4910e-6c91-42a0-ba96-175f9f481742', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'KEROSENE', 'OVERALL', '134.67', '134.67', null, 'reported'),
  ('6eaf96e6-d3cf-4281-b148-ccdc5b4944c4', '152fee31-2882-4273-9221-7677c16cecef', 'RON_95', 'CALTEX', '84.90', '93.70', null, 'reported'),
  ('73a70172-81cb-4cee-a3d5-c8dccf23f002', '152fee31-2882-4273-9221-7677c16cecef', 'RON_95', 'SHELL', '81.80', '88.60', null, 'reported'),
  ('76691698-c2b4-410e-87f8-dc9a7eb13727', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'DIESEL', 'SHELL', '91.00', '91.70', null, 'reported'),
  ('7d4cff5f-70e0-4bcf-93a7-db915a65c1d5', '152fee31-2882-4273-9221-7677c16cecef', 'RON_95', 'PETRON', '75.40', '76.00', null, 'reported'),
  ('7d523447-b1a4-4cce-98a5-20b9cb8ba350', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_95', 'SHELL', '82.10', '83.10', null, 'reported'),
  ('833af3d0-dbc8-47be-9b3f-d7a7f2ae5453', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_95', 'TOTAL', '84.90', '84.90', null, 'reported'),
  ('86939bfe-7f04-44aa-b4d5-50acd86d8654', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_91', 'PETRON', '74.50', '74.50', null, 'reported'),
  ('996ab954-c498-4bb4-91e2-8833c732fac3', '152fee31-2882-4273-9221-7677c16cecef', 'DIESEL', 'PETRON', '86.50', '89.10', '89.10', 'reported'),
  ('b291c64d-d363-4e4d-9f4a-58c97036ac8f', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_95', 'OVERALL', '71.99', '84.90', null, 'reported'),
  ('c5c5046b-73af-44b0-a727-be86da75f640', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_95', 'PETRON', '75.50', '75.50', null, 'reported'),
  ('c65a0c94-5226-4d4c-ae24-c7fb7685ae9a', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_91', 'SHELL', '76.40', '77.40', null, 'reported'),
  ('c805a711-0d79-48cc-bed7-2f4d0817bcdc', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_91', 'UNIOIL', null, null, null, 'no_outlet'),
  ('d5d35923-02be-4ec7-aa14-28b4ec50cfb7', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'RON_95', 'INDEPENDENT', '71.50', '73.99', null, 'reported'),
  ('d826cf86-f298-4fe1-b818-0e749c5ddcc9', '152fee31-2882-4273-9221-7677c16cecef', 'DIESEL', 'OVERALL', '81.50', '93.84', '89.10', 'reported'),
  ('e164f375-470e-4326-8e5c-6e895015f7d5', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_95', 'CALTEX', '83.50', '83.50', null, 'reported'),
  ('e89f93e6-56cb-4678-b8cb-f049bf0d42f8', '1cae152d-3be2-4e5b-a2d0-6ff261db6e20', 'RON_91', 'SEAOIL', null, null, null, 'no_outlet'),
  ('f740611c-e9f3-45e9-8228-653bcbcada06', '1db4990c-094e-4fe9-ba3e-9c675b149ef1', 'DIESEL', 'OVERALL', '82.20', '90.13', null, 'reported')
on conflict (id) do nothing;

