#!/usr/bin/env python3
"""Record, as an issue comment, the commits that predate the `Refs:` convention.

Every commit now names the record that explains it (docs/commit-conventions.md),
and GitHub turns that into a *referenced this issue* event pointing back at the
commit. The thirty commits written before the rule carry no trailer and get no
event.

Adding one retroactively means rewriting from the root commit, which moves all
thirty shas. This repository cites its own shas in thirteen places, two of them
inside sealed records under openspec/bugs/archive/, and the live bodies of #10
and #11 embed three more. The cross-references derived from those would degrade
to nothing *without erroring*, because change_for_commit() resolves on a unique
match or not at all. So history is left alone and the link is written as a
comment instead: weaker, issue-to-commit only, and additive.

This is not part of the board projection. The sync writes bodies, labels,
status and edges, and never comments; nothing here is regenerated by it, and a
board rebuilt from scratch loses these. Run the script again in that case.

Idempotent: each comment carries an invisible marker and an issue that already
has one is skipped, so no ledger is stored anywhere.

Usage:  python3 scripts/backfill-commit-links.py [--dry-run]

Requires: gh CLI authenticated.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

MARKER = "<!-- backfill-commit-links -->"

# Duplicated from scripts/sync-project-board.py, and from .githooks/commit-msg.
ARCHIVE_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}-")

TRAILER_GREP = r"^Refs: [^ ]+ #[0-9]+$"

# [^/\n]+ rather than [^/]+: under re.M the negated class still matches a
# newline, so a file directly under openspec/bugs/ lets the name run into the
# next path and swallow the real record. Same fix in sync-project-board.py.
RECORD_PATH_RE = re.compile(
    r"^openspec/(changes|bugs)/(?:archive/)?([^/\n]+)/", re.M
)

TITLE_PREFIXES = {"change": "[change] ", "bug": "[bug] "}

# Two commits no path can map, each for its own reason. Written out rather than
# inferred, because a heuristic that reached these would reach further.
OVERRIDES = {
    # The fix landed a day before the bug was filed, so it touches the code it
    # repaired and nothing under openspec/bugs/.
    "dbcb277": "board-issue-links-are-relative",
    # Shipped the bug-archive workflow with no record whatsoever. The record was
    # written afterwards, by add-commit-issue-links, so no path can point at it.
    "63f9b00": "add-bug-archive-workflow",
}


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args], capture_output=True, text=True, cwd=REPO_ROOT
    )
    if result.returncode != 0:
        sys.exit(f"git {' '.join(args)} failed:\n{result.stderr.strip()}")
    return result.stdout.rstrip("\n")


def gh(*args: str) -> str:
    result = subprocess.run(
        ["gh", *args], capture_output=True, text=True, cwd=REPO_ROOT
    )
    if result.returncode != 0:
        sys.exit(f"gh {' '.join(args)} failed:\n{result.stderr.strip()}")
    return result.stdout.strip()


def known_records() -> dict[str, str]:
    """Every record name on disk, mapped to its kind."""
    found: dict[str, str] = {}
    for tree, kind in (("changes", "change"), ("bugs", "bug")):
        base = REPO_ROOT / "openspec" / tree
        for directory in (base, base / "archive"):
            if not directory.is_dir():
                continue
            for path in sorted(directory.iterdir()):
                if path.is_dir() and path.name != "archive":
                    found[ARCHIVE_DATE_RE.sub("", path.name)] = kind
    return found


def untrailered_commits() -> list[tuple[str, str, str]]:
    """(short sha, subject, full sha) for commits carrying no Refs: trailer,
    oldest first. A commit that has one already has its event."""
    # Two passes rather than one. Putting %(trailers:...) in the same --format
    # breaks line-based parsing: `separator` is not honoured for it here, so a
    # commit with two Refs: lines emits two lines and the fields no longer line
    # up with the commits.
    trailered = set(
        git("log", "-E", "--grep", TRAILER_GREP, "--format=%H").splitlines()
    )
    out = []
    for line in git("log", "--reverse", "--format=%h%x1f%s%x1f%H").splitlines():
        short, subject, full = line.split("\x1f")
        if full not in trailered:
            out.append((short, subject, full))
    return out


def records_for(full_sha: str, short_sha: str) -> set[str]:
    override = OVERRIDES.get(short_sha)
    if override:
        return {override}
    touched = git("show", "--name-only", "--format=", full_sha)
    return {
        ARCHIVE_DATE_RE.sub("", m.group(2))
        for m in RECORD_PATH_RE.finditer(touched)
        if m.group(2) != "archive"
    }


def issue_numbers() -> dict[str, int]:
    raw = gh("issue", "list", "--state", "all", "--limit", "300",
             "--json", "number,title")
    return {i["title"]: i["number"] for i in json.loads(raw)}


def has_marker(number: int) -> bool:
    raw = gh("issue", "view", str(number), "--json", "comments")
    return any(MARKER in c["body"] for c in json.loads(raw)["comments"])


def comment_body(commits: list[tuple[str, str]]) -> str:
    lines = [
        MARKER,
        "**Commits predating the `Refs:` convention**",
        "",
        "These landed before commit messages named the record that explains",
        "them, so they produced no reference event. Recorded here instead —",
        "see `docs/commit-conventions.md`.",
        "",
    ]
    lines += [f"- {sha} {subject}" for sha, subject in commits]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="print every comment that would be posted")
    args = parser.parse_args()

    records = known_records()
    numbers = issue_numbers()

    by_issue: dict[int, list[tuple[str, str]]] = {}
    unmapped: list[tuple[str, str]] = []
    unknown: list[tuple[str, str]] = []

    for short, subject, full in untrailered_commits():
        names = records_for(full, short)
        if not names:
            unmapped.append((short, subject))
            continue
        for name in sorted(names):
            kind = records.get(name)
            if kind is None:
                unknown.append((short, name))
                continue
            number = numbers.get(TITLE_PREFIXES[kind] + name)
            if number is None:
                unknown.append((short, name))
                continue
            by_issue.setdefault(number, []).append((short, subject))

    posted = skipped = 0
    for number in sorted(by_issue):
        commits = by_issue[number]
        if not args.dry_run and has_marker(number):
            print(f"  #{number:<3} already backfilled, skipping")
            skipped += 1
            continue
        body = comment_body(commits)
        if args.dry_run:
            print(f"  #{number} would receive:")
            print("\n".join("      " + ln for ln in body.splitlines()))
            print()
        else:
            gh("issue", "comment", str(number), "--body", body)
            print(f"  #{number:<3} commented, {len(commits)} commit(s)")
        posted += 1

    print()
    if unmapped:
        print(f"{len(unmapped)} commit(s) map to no record:")
        for sha, subject in unmapped:
            print(f"  {sha}  {subject}")
        print("  These predate the rule and are named in "
              "docs/commit-conventions.md as the historical exception.")
    if unknown:
        print(f"{len(unknown)} reference(s) resolved to no issue:")
        for sha, name in unknown:
            print(f"  {sha}  ->  {name}")

    verb = "would comment on" if args.dry_run else "commented on"
    print(f"\n{posted} issue(s) {verb}"
          + (f", {skipped} already done." if skipped else "."))


if __name__ == "__main__":
    main()
