#!/usr/bin/env python3
"""Generate supabase/seed.sql from the recorded DOE loads.

DOE reference prices are loaded by hand, by a person reading a published PDF and
calling load_doe_reference_prices() with a payload they typed. That payload was
never saved anywhere, so `supabase db reset` — which re-runs migrations and drops
everything they did not create — destroyed it, and the only way back was to find
the same document and read the same table again.

The mechanism to prevent that already existed and was empty: config.toml carries
[db.seed] enabled = true, and Supabase loads supabase/seed.sql after every reset.
This writes that file.

Generated, never hand-edited. A hand-maintained seed is a second hand-typed
payload, which is the original problem one level along. Regenerate after every
load; `docs/doe-manual-load-procedure.md` says so as its last step.

Committing it also makes the loaded figures reviewable in git, which a payload
living only inside a database never was.

Usage:  python3 scripts/generate-doe-seed.py [--linked] [--stdout]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SEED = REPO_ROOT / "supabase" / "seed.sql"

# Order matters: each table references the one before it.
TABLES = (
    ("doe_load_runs",
     ("id", "doe_region_code", "status", "source_url", "period_start",
      "period_end", "period_label", "failure_reason", "started_at",
      "recorded_at")),
    ("doe_locality_reports",
     ("id", "run_id", "doe_source_label", "status")),
    ("doe_reference_prices",
     ("id", "locality_report_id", "fuel_type_code", "brand_code",
      "min_price", "max_price", "common_price", "brand_presence")),
)


def db(sql: str, linked: bool) -> list[dict]:
    result = subprocess.run(
        ["supabase", "db", "query", sql, "--linked" if linked else "--local"],
        capture_output=True, text=True, cwd=REPO_ROOT,
    )
    if result.returncode != 0:
        sys.exit(f"db query failed:\n{result.stdout.strip()}\n{result.stderr.strip()}")
    try:
        return json.loads(result.stdout).get("rows") or []
    except json.JSONDecodeError:
        return []


def lit(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--linked", action="store_true",
                        help="read from the linked hosted project")
    parser.add_argument("--stdout", action="store_true",
                        help="print instead of writing supabase/seed.sql")
    args = parser.parse_args()

    out = [
        "-- GENERATED by scripts/generate-doe-seed.py. Do not edit by hand.",
        "--",
        "-- Supabase loads this after every `db reset`, which is what stops a reset",
        "-- destroying DOE data that was loaded by hand and saved nowhere else.",
        "-- Regenerate after each load; see docs/doe-manual-load-procedure.md.",
        "--",
        "-- ON CONFLICT DO NOTHING so this is safe to apply to a database that",
        "-- already holds these runs, rather than only to an empty one.",
        "",
    ]
    counts = []
    for table, columns in TABLES:
        rows = db(f"select {', '.join(columns)} from {table} order by 1", args.linked)
        counts.append((table, len(rows)))
        if not rows:
            out.append(f"-- {table}: no rows recorded")
            continue
        out.append(f"insert into public.{table} ({', '.join(columns)}) values")
        values = [
            "  (" + ", ".join(lit(row.get(c)) for c in columns) + ")"
            for row in rows
        ]
        out.append(",\n".join(values))
        out.append("on conflict (id) do nothing;")
        out.append("")

    text = "\n".join(out) + "\n"
    if args.stdout:
        print(text)
    else:
        SEED.parent.mkdir(parents=True, exist_ok=True)
        SEED.write_text(text)
        print(f"  wrote {SEED.relative_to(REPO_ROOT)}")
    for table, n in counts:
        print(f"    {table:<24}{n:>4} row(s)")


if __name__ == "__main__":
    main()
