#!/usr/bin/env python3
"""Project the OpenSpec workflow onto a GitHub Project board.

The board is DERIVED, never maintained. Every run recomputes each change's
status and progress from `openspec/` — a change's directory says which column
it belongs in, and its task checkboxes give its progress:

    openspec/changes/<name>/           0 tasks done   ->  Proposed
    openspec/changes/<name>/           some done      ->  In Progress
    openspec/changes/<name>/           all done       ->  Ready to archive
    openspec/changes/archive/<name>/                  ->  Done

Because nothing is stored, the board cannot drift out of sync. The only way for
it to be wrong is for openspec/ to be wrong, in which case it is faithfully
reporting a real problem.

This is one-directional. Editing a card on the board does not move the work,
and the next run will overwrite it.

Usage:  python3 scripts/sync-project-board.py [--dry-run]

Requires: gh CLI authenticated with `project` scope (gh auth refresh -s project)
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = "zipz4per/gas-price-tracker"
PROJECT_NUMBER = "6"
PROJECT_OWNER = "zipz4per"

# Every issue is assigned to the repository owner so the board's Assignees
# column is populated and filtering by assignee returns the whole project.
ISSUE_ASSIGNEE = "zipz4per"

# Custom field, not GitHub's built-in "Status". The built-in one is reserved:
# it cannot be deleted, recreated, or extended from the CLI, so relying on it
# would make the board impossible to set up without clicking through the web UI.
STATUS_FIELD = "OpenSpec Status"

PROPOSED, IN_PROGRESS, READY, DONE = (
    "Proposed",
    "In Progress",
    "Ready to archive",
    "Done",
)

ISSUE_TITLE_PREFIX = "[change] "
ARCHIVE_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}-")

REPO_ROOT = Path(__file__).resolve().parent.parent
CHANGES_DIR = REPO_ROOT / "openspec" / "changes"
ARCHIVE_DIR = CHANGES_DIR / "archive"


def gh(*args: str, check: bool = True) -> str:
    """Run a gh command and return stdout. Fails loudly rather than guessing."""
    result = subprocess.run(
        ["gh", *args], capture_output=True, text=True, cwd=REPO_ROOT
    )
    if check and result.returncode != 0:
        raise RuntimeError(f"gh {' '.join(args)}\n{result.stderr.strip()}")
    return result.stdout.strip()


@dataclass
class Change:
    name: str
    path: Path
    archived: bool
    done: int
    total: int

    @property
    def status(self) -> str:
        if self.archived:
            return DONE
        if self.total == 0 or self.done == 0:
            return PROPOSED
        if self.done == self.total:
            return READY
        return IN_PROGRESS

    @property
    def issue_title(self) -> str:
        return f"{ISSUE_TITLE_PREFIX}{self.name}"

    @property
    def progress(self) -> str:
        return f"{self.done}/{self.total}" if self.total else "no tasks"


def count_tasks(change_dir: Path) -> tuple[int, int]:
    """Count completed vs total tasks. A change with no tasks.md is not an
    error — some changes are pure planning — so it reports zero progress."""
    tasks = change_dir / "tasks.md"
    if not tasks.is_file():
        return 0, 0
    text = tasks.read_text(encoding="utf-8")
    done = len(re.findall(r"(?m)^- \[x\] ", text))
    todo = len(re.findall(r"(?m)^- \[ \] ", text))
    return done, done + todo


def discover_changes() -> list[Change]:
    changes: list[Change] = []

    for d in sorted(CHANGES_DIR.iterdir()) if CHANGES_DIR.is_dir() else []:
        if not d.is_dir() or d.name == "archive":
            continue
        done, total = count_tasks(d)
        changes.append(Change(d.name, d, False, done, total))

    for d in sorted(ARCHIVE_DIR.iterdir()) if ARCHIVE_DIR.is_dir() else []:
        if not d.is_dir():
            continue
        # Archived directories carry a YYYY-MM-DD- prefix; the change's real
        # name is what the issue title must match, so strip it.
        name = ARCHIVE_DATE_RE.sub("", d.name)
        done, total = count_tasks(d)
        changes.append(Change(name, d, True, done, total))

    return changes


def build_issue_body(change: Change) -> str:
    """Body is the change's tasks.md verbatim — OpenSpec already writes GitHub
    checkbox markdown, so GitHub renders a native task list with a progress bar
    without any transformation."""
    rel = change.path.relative_to(REPO_ROOT).as_posix()
    lines = [
        "<!-- Generated by scripts/sync-project-board.py. Edits here are overwritten. -->",
        "",
        f"**Status:** {change.status} · **Tasks:** {change.progress}",
        "",
        f"- [proposal]({rel}/proposal.md)",
    ]
    if (change.path / "design.md").is_file():
        lines.append(f"- [design]({rel}/design.md)")
    specs = sorted((change.path / "specs").rglob("spec.md")) if (change.path / "specs").is_dir() else []
    for spec in specs:
        lines.append(f"- [spec: {spec.parent.name}]({spec.relative_to(REPO_ROOT).as_posix()})")
    lines.append("")

    tasks = change.path / "tasks.md"
    if tasks.is_file():
        lines.append("---")
        lines.append("")
        lines.append(tasks.read_text(encoding="utf-8").rstrip())
    else:
        lines.append("_No tasks file._")

    return "\n".join(lines) + "\n"


def find_issue(title: str) -> dict | None:
    """Match by title. No stored ids: if an issue is deleted the next run
    recreates it rather than failing on a dangling reference."""
    raw = gh(
        "issue", "list", "--repo", REPO, "--state", "all",
        "--limit", "200", "--json", "number,title,state,body,url,assignees",
    )
    for issue in json.loads(raw or "[]"):
        if issue["title"] == title:
            return issue
    return None


def project_items() -> dict[str, str]:
    """Map issue url -> project item id, fetched once per run.

    Newly added items are folded into this map from the item-add response
    rather than re-queried: `item-add` returns before `item-list` reflects the
    new item, so looking it up immediately is a race.
    """
    raw = gh(
        "project", "item-list", PROJECT_NUMBER,
        "--owner", PROJECT_OWNER, "--limit", "200", "--format", "json",
    )
    items: dict[str, str] = {}
    for item in json.loads(raw or "{}").get("items", []):
        content = item.get("content") or {}
        if content.get("url"):
            items[content["url"]] = item["id"]
    return items


def sync(dry_run: bool) -> int:
    changes = discover_changes()
    if not changes:
        print("No changes found under openspec/changes/.")
        return 1

    print(f"Found {len(changes)} change(s)\n")
    on_board = {} if dry_run else project_items()
    actions = 0

    for change in changes:
        body = build_issue_body(change)
        issue = find_issue(change.issue_title)
        want_state = "CLOSED" if change.archived else "OPEN"

        print(f"  {change.name}")
        print(f"    status   {change.status}  ({change.progress})")

        if dry_run:
            print(f"    issue    {'update' if issue else 'create'} (dry run)")
            print(f"    board    set {STATUS_FIELD} = {change.status} (dry run)\n")
            continue

        if issue is None:
            url = gh(
                "issue", "create", "--repo", REPO,
                "--title", change.issue_title, "--body", body,
                "--assignee", ISSUE_ASSIGNEE,
            ).splitlines()[-1]
            issue = {"url": url, "number": url.rsplit("/", 1)[-1], "state": "OPEN",
                     "body": body, "assignees": [{"login": ISSUE_ASSIGNEE}]}
            print(f"    issue    created {url}")
            actions += 1
        else:
            url = issue["url"]
            if issue.get("body", "").strip() != body.strip():
                gh("issue", "edit", str(issue["number"]), "--repo", REPO, "--body", body)
                print(f"    issue    body updated")
                actions += 1
            else:
                print(f"    issue    up to date")

        assignees = {a["login"] for a in issue.get("assignees", [])}
        if ISSUE_ASSIGNEE not in assignees:
            gh("issue", "edit", str(issue["number"]), "--repo", REPO,
               "--add-assignee", ISSUE_ASSIGNEE)
            print(f"    issue    assigned to {ISSUE_ASSIGNEE}")
            actions += 1

        # An archived change closes its issue, so the repo's open issues mean
        # "work in flight" without needing the board next to them.
        if issue.get("state", "OPEN").upper() != want_state:
            verb = "close" if want_state == "CLOSED" else "reopen"
            gh("issue", verb, str(issue["number"]), "--repo", REPO)
            print(f"    issue    {verb}d")
            actions += 1

        if url not in on_board:
            added = gh("project", "item-add", PROJECT_NUMBER, "--owner", PROJECT_OWNER,
                       "--url", url, "--format", "json")
            on_board[url] = json.loads(added)["id"]
            print(f"    board    card added")
            actions += 1
        else:
            print(f"    board    card present")

        gh(
            "project", "item-edit",
            "--project-id", project_id(),
            "--id", on_board[url],
            "--field-id", status_field_id(),
            "--single-select-option-id", status_option_id(change.status),
        )
        print(f"    board    {STATUS_FIELD} = {change.status}\n")

    print(f"{'Dry run — nothing changed.' if dry_run else f'{actions} change(s) applied.'}")
    return 0


# --- project metadata, resolved once per run -------------------------------

_cache: dict[str, object] = {}


def project_id() -> str:
    if "pid" not in _cache:
        raw = gh("project", "view", PROJECT_NUMBER, "--owner", PROJECT_OWNER, "--format", "json")
        _cache["pid"] = json.loads(raw)["id"]
    return _cache["pid"]  # type: ignore[return-value]


def _status_field() -> dict:
    if "field" not in _cache:
        raw = gh("project", "field-list", PROJECT_NUMBER, "--owner", PROJECT_OWNER, "--format", "json")
        for f in json.loads(raw)["fields"]:
            if f["name"] == STATUS_FIELD:
                _cache["field"] = f
                break
        else:
            raise RuntimeError(f"project field {STATUS_FIELD!r} not found")
    return _cache["field"]  # type: ignore[return-value]


def status_field_id() -> str:
    return _status_field()["id"]


def status_option_id(name: str) -> str:
    for opt in _status_field().get("options", []):
        if opt["name"] == name:
            return opt["id"]
    raise RuntimeError(f"{STATUS_FIELD} has no option {name!r}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="show what would change without touching GitHub")
    args = parser.parse_args()
    try:
        return sync(args.dry_run)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
